apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hamp9hzhb-nodejs-gitops
  description: This is GitOps manifest for hamp9hzhb-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=hamp9hzhb-nodejs
    backstage.io/kubernetes-id: hamp9hzhb-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: hamp9hzhb-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hamp9hzhb-nodejs
