apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hamp9hzhb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hamp9hzhb-nodejs 
  name: hamp9hzhb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hamp9hzhb-nodejs 
